apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: fbc-kas-comp
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: fbc-kas-comp
    app.kubernetes.io/part-of: fbc-kas-app
  name: fbc-kas-complzu4
spec:
  port:
    targetPort: 50051
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: fbc-kas-comp
    weight: 100
status: {}
