apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: fbc-kas-comp
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: fbc-kas-comp
    app.kubernetes.io/part-of: fbc-kas-app
  name: fbc-kas-comp
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: fbc
      app.kubernetes.io/instance: fbc-kas-comp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: fbc
        app.kubernetes.io/instance: fbc-kas-comp
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/dev-release-team-tenant/fbc-kas-app/fbc-kas-comp@sha256:bc5e390115cdfab83db1767dfd7f2865cdb83d4b77866bf4c8df0733aab28a80
        name: fbc
        ports:
        - containerPort: 50051
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 512Mi
status: {}
