apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: fbc-kas-comp
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: fbc-kas-comp
    app.kubernetes.io/part-of: fbc-kas-app
  name: fbc-kas-comp
spec:
  ports:
  - port: 50051
    targetPort: 50051
  selector:
    app.kubernetes.io/instance: fbc-kas-comp
status:
  loadBalancer: {}
